repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-yaml
    - id: check-xml
    - id: check-json
    - id: check-added-large-files
    - id: check-docstring-first
    - id: debug-statements
    - id: name-tests-test
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.1
    hooks:
    - id: reorder-python-imports
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.1
    hooks:
    - id: pyupgrade
      args: [--py37-plus]
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black
      language_version: python3.10
      args: # arguments to configure black
        - --line-length=120
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
